--Quản lý bán hàng
USE QLBH
SET DATEFORMAT DMY
--I
--Câu 11
CREATE TRIGGER trg_ins_hd ON HOADON
FOR INSERT
AS
BEGIN
	IF EXISTS (SELECT *
		FROM INSERTED, KHACHHANG
		WHERE INSERTED.MAKH = KHACHHANG.MAKH
		AND NGHD < NGDK)
	BEGIN
		RAISERROR ('LOI: NGAY HOA DON KHONG HOP IE!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI HOA DON THANH CONG!'
	END
END

--Câu 12
CREATE TRIGGER trg_ins_bh ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT *
		FROM INSERTED, NHANVIEN
		WHERE INSERTED.MANV = NHANVIEN.MANV
		AND NGHD < NGVL)
	BEGIN
		RAISERROR ('LOI: NGAY BAN HANG KHONG HOP IE!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI NHAN VIEN THANH CONG!'
	END
END

--Câu 13
CREATE TRIGGER trg_ins_tg ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT *
		FROM INSERTED I
		JOIN (
			SELECT C.SOHD, SUM(C.SL * SP.GIA) AS THANHTIEN
			FROM CTHD C
			JOIN SANPHAM SP ON C.MASP = SP.MASP
			GROUP BY C.SOHD
		) TG ON TG.SOHD = I.SOHD
		WHERE I.TRIGIA <> TG.THANHTIEN)
	BEGIN
		RAISERROR ('LOI: TRI GIA KHONG HOP IE!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI HOA DON THANH CONG!'
	END
END

--Câu 14
CREATE TRIGGER trg_ins_kh ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT *
		FROM KHACHHANG K
		JOIN (
			SELECT MAKH, SUM(TRIGIA) AS TONGTRIGIA
			FROM HOADON
			WHERE MAKH IS NOT NULL
			GROUP BY MAKH
		) HD ON K.MAKH = HD.MAKH
		JOIN INSERTED I ON I.MAKH = K.MAKH
		WHERE K.DOANHSO <> HD.TONGTRIGIA)
	BEGIN
		RAISERROR ('LOI: DOANH SO KHONG HOP LE!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI HOA DON THANH CONG!'
	END
END
--Quản lý giáo vụ
USE QLGV
SET DATEFORMAT DMY
--I
--CÂU 9
CREATE TRIGGER trg_ins_lop ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT *
		FROM INSERTED I
		JOIN HOCVIEN HV ON HV.MAHV = I.TRGLOP
		WHERE I.TRGLOP IS NOT NULL AND I.MALOP <> HV.MALOP)
	BEGIN
		RAISERROR ('LOI: LOP TRUONG KHONG HOP LE!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI LOP THANH CONG!'
	END
END

--CÂU 10
CREATE TRIGGER trg_ins_gv ON KHOA
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT *
		FROM INSERTED I
		JOIN GIAOVIEN GV ON GV.MAGV = I.TRGKHOA 
		WHERE I.TRGKHOA IS NOT NULL AND (I.TRGKHOA <> GV.MAGV OR GV.HOCVI NOT IN ('TS', 'PTS')))
	BEGIN
		RAISERROR ('LOI: LOP TRUONG KHONG HOP LE!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI THANH CONG!'
	END
END

--CÂU 15
CREATE TRIGGER trg_ins_kqt ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT *
		FROM INSERTED I
		JOIN HOCVIEN HV ON HV.MAHV = I.MAHV
		WHERE NOT EXISTS (
			SELECT *
			FROM GIANGDAY GD
			WHERE GD.MALOP = HV.MALOP
			AND GD.MAMH = I.MAMH
			AND I.NGTHI > GD.DENNGAY
		))
	BEGIN
		RAISERROR ('LOI: HOC VIEN CHI DUOC THI SAU KHI LOP HOC XONG MON!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI THANH CONG!'
	END
END
--CÂU 16
CREATE TRIGGER trg_ins_gd ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT *
FROM (
            SELECT MALOP, HOCKY, NAM
            FROM INSERTED I
            GROUP BY MALOP, HOCKY, NAM
        ) IA
        WHERE (
            SELECT COUNT(*)
            FROM GIANGDAY GD
            WHERE GD.MALOP = IA.MALOP
              AND GD.HOCKY = IA.HOCKY
              AND GD.NAM   = IA.NAM
        ) > 3)
	BEGIN
		RAISERROR ('LOI: MOI HOC KY MOI LOP CHI HOC TOI DA 3 MON!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI THANH CONG!'
	END
END

--CÂU 17
CREATE TRIGGER trg_ins_hvien ON HOCVIEN
FOR INSERT, UPDATE, DELETE
AS
BEGIN
	IF EXISTS (SELECT *
		FROM (
            SELECT MALOP FROM INSERTED
			UNION
            SELECT MALOP FROM DELETED
        ) IA
        WHERE (
            SELECT COUNT(*)
            FROM HOCVIEN HV
            WHERE HV.MALOP = IA.MALOP
		) <> (
			SELECT SISO
			FROM LOP L
			WHERE L.MALOP = IA.MALOP
		)
	)
	BEGIN
		RAISERROR ('LOI: SI SO LOP KHONG DUNG VOI SO LUONG HOC VIEN!', 16, 1) ;
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI THANH CONG!'
	END
END

------Câu 18
ALTER TABLE DIEUKIEN ADD CONSTRAINT CHK_MAMH_KHAC CHECK (MAMH <> MAMH_TRUOC);

CREATE TRIGGER trg_ins_upd_DIEUKIEN
ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (SELECT * FROM DIEUKIEN t1, inserted t2 
               WHERE t1.MAMH = t2.MAMH_TRUOC AND t1.MAMH_TRUOC = t2.MAMH)
    BEGIN
        PRINT 'Lỗi: Tồn tại chu kỳ hoặc cặp môn học đối xứng!'
        ROLLBACK TRANSACTION
    END
END;


------Câu 19
CREATE TRIGGER trg_GIAOVIEN_MUCLUONG
ON GIAOVIEN
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT * FROM GIAOVIEN g, inserted i
        WHERE g.HOCVI = i.HOCVI AND g.HOCHAM = i.HOCHAM AND g.HESO = i.HESO
        AND g.MUCLUONG <> i.MUCLUONG
    )
    BEGIN
        PRINT 'Lỗi: Mức lương không đồng nhất với học vị, học hàm và hệ số!'
        ROLLBACK TRANSACTION
    END
END;

--------Câu 20
CREATE TRIGGER trg_ins_upd_KetQuaThi_LanThi
ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT * FROM inserted i
        WHERE i.LANTHI > 1 
          AND EXISTS (
              SELECT 1 FROM KETQUATHI kq 
              WHERE kq.MAHV = i.MAHV 
                AND kq.MAMH = i.MAMH 
                AND kq.LANTHI = i.LANTHI - 1 
                AND kq.DIEM >= 5
          )
    )
    BEGIN
        PRINT 'Lỗi: Học viên đã đạt ở lần thi trước, không được thi lại.'
        ROLLBACK TRANSACTION
    END
END;
---------Câu 21
CREATE TRIGGER trg_NgayThi_Sau_Lon_Hon_Truoc
ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT * FROM inserted i
        JOIN KETQUATHI kq ON i.MAHV = kq.MAHV AND i.MAMH = kq.MAMH
        WHERE i.LANTHI > kq.LANTHI AND i.NGTHI <= kq.NGTHI
    )
    BEGIN
        PRINT 'Lỗi: Ngày thi lần sau phải lớn hơn ngày thi lần trước.'
        ROLLBACK TRANSACTION
    END
END;
----------Câu 22
CREATE TRIGGER trg_KiemTraMonTruoc
ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT * FROM inserted i
        JOIN DIEUKIEN dk ON i.MAMH = dk.MAMH
        WHERE NOT EXISTS (
            SELECT 1 FROM KETQUATHI kq 
            WHERE kq.MAHV = i.MAHV 
              AND kq.MAMH = dk.MAMH_TRUOC 
              AND kq.NGTHI < i.NGTHI 
              AND kq.DIEM >= 5
        )
    )
    BEGIN
        PRINT 'Lỗi: Học viên chưa hoàn thành môn học trước.'
        ROLLBACK TRANSACTION
    END
END;
---------Câu 23
CREATE TRIGGER trg_GiaoVien_Day_Dung_Khoa
ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT * FROM inserted i
        JOIN GIAOVIEN g ON i.MAGV = g.MAGV
        JOIN MONHOC m ON i.MAMH = m.MAMH
        WHERE g.MAKHOA <> m.MAKHOA
    )
    BEGIN
        PRINT 'Lỗi: Giáo viên không thể dạy môn học của khoa khác.'
        ROLLBACK TRANSACTION
    END
END;