----23
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
JOIN LOP L ON GV.MAGV = L.MAGVCN
JOIN GIANGDAY GD ON GD.MAGV = GV.MAGV
                AND GD.MALOP = L.MALOP;


-----27
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HoTen, HV.MALOP
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
WHERE KQ.DIEM BETWEEN 9 AND 10
GROUP BY HV.MAHV, HV.HO, HV.TEN, HV.MALOP
HAVING COUNT(*) >= ALL (
    SELECT COUNT(*)
    FROM HOCVIEN H
    JOIN KETQUATHI K ON H.MAHV = K.MAHV
    WHERE K.DIEM BETWEEN 9 AND 10
      AND H.MALOP = HV.MALOP
    GROUP BY H.MAHV
);


--------29
SELECT GV.MAGV, GV.HOTEN, GD.NAM, GD.HOCKY
FROM GIAOVIEN GV
JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
GROUP BY GV.MAGV, GV.HOTEN, GD.NAM, GD.HOCKY
HAVING COUNT(*) >= ALL (
    SELECT COUNT(*)
    FROM GIANGDAY G
    WHERE G.NAM = GD.NAM
      AND G.HOCKY = GD.HOCKY
    GROUP BY G.MAGV
)
ORDER BY GD.NAM, GD.HOCKY;

