------26
SELECT TOP 3 MAKH, HOTEN, DOANHSO
FROM KHACHHANG
ORDER BY DOANHSO DESC;

-------27 
SELECT MASP, TENSP
FROM SANPHAM
WHERE GIA IN (
    SELECT DISTINCT TOP 3 GIA
    FROM SANPHAM
    ORDER BY GIA DESC
);
-------------28
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = N'Thai Lan' 
  AND GIA IN (
      SELECT DISTINCT TOP 3 GIA
      FROM SANPHAM
      ORDER BY GIA DESC
  );
-------29 
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = N'Trung Quoc'
  AND GIA IN (
      SELECT DISTINCT TOP 3 GIA
      FROM SANPHAM
      WHERE NUOCSX = N'Trung Quoc'
      ORDER BY GIA DESC
  );

-------34
SELECT 
    NGHD, 
    SUM(TRIGIA) AS DoanhThuNgay 
FROM 
    HOADON
GROUP BY 
    NGHD
ORDER BY 
    NGHD; 

--------36
SELECT 
    YEAR(NGHD) AS Nam,
    MONTH(NGHD) AS Thang,
    SUM(TRIGIA) AS DoanhThuThang
FROM 
    HOADON
WHERE 
    YEAR(NGHD) = 2006
GROUP BY 
    YEAR(NGHD), MONTH(NGHD)
ORDER BY 
    Nam, Thang;
------38
SELECT HD.SOHD
FROM HOADON HD
JOIN CTHD CT ON HD.SOHD = CT.SOHD
JOIN SANPHAM SP ON CT.MASP = SP.MASP
WHERE SP.NUOCSX = N'Viet Nam'
GROUP BY HD.SOHD
HAVING COUNT(DISTINCT CT.MASP) = 3;


-----43 
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3;

------44
SELECT TOP 1 T1.MAKH, T1.HOTEN, COUNT(T2.SOHD) AS SoLanMuaHang
FROM KHACHHANG T1
INNER JOIN HOADON T2 ON T1.MAKH = T2.MAKH
WHERE T1.MAKH IN (
    SELECT TOP 10 MAKH
    FROM KHACHHANG
    ORDER BY DOANHSO DESC
)
GROUP BY T1.MAKH, T1.HOTEN
ORDER BY SoLanMuaHang DESC;