----23
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
JOIN LOP L ON GV.MAGV = L.MAGVCN
JOIN GIANGDAY GD ON GD.MAGV = GV.MAGV
                AND GD.MALOP = L.MALOP;
---------25



-----27
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HoTen, HV.MALOP
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
WHERE KQ.DIEM BETWEEN 9 AND 10
GROUP BY HV.MAHV, HV.HO, HV.TEN, HV.MALOP
HAVING COUNT(*) >= ALL (
    SELECT COUNT(*)
    FROM HOCVIEN H
    JOIN KETQUATHI K ON H.MAHV = K.MAHV
    WHERE K.DIEM BETWEEN 9 AND 10
      AND H.MALOP = HV.MALOP
    GROUP BY H.MAHV
);


--------29
SELECT GV.MAGV, GV.HOTEN, GD.NAM, GD.HOCKY
FROM GIAOVIEN GV
JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
GROUP BY GV.MAGV, GV.HOTEN, GD.NAM, GD.HOCKY
HAVING COUNT(*) >= ALL (
    SELECT COUNT(*)
    FROM GIANGDAY G
    WHERE G.NAM = GD.NAM
      AND G.HOCKY = GD.HOCKY
    GROUP BY G.MAGV
)
ORDER BY GD.NAM, GD.HOCKY;

--------34 
SELECT HOTEN,CMND
FROM BENHNHAN
WHERE DOITUONG = 'BHYT' OR DIACHI = 'DONG NAI'
ORDER BY SLPT DESC;

SELECT kb.MAKB, bn.MABN, bn.HOTEN
FROM BENHNHAN bn JOIN KHAMBENH kb ON bn.MABN = kb.MABN
WHERE YEAR(NGSINH) > 2020 AND BENH = N'tim mach';

---------35 
SELECT kb.MABN, bn.HOTEN, COUNT(MAKB) AS SL
FROM BENHNHAN bn JOIN KHAMBENH kb ON bn.MABN = kb.MABN
WHERE YEAR(BATDAU) > 2020
GROUP BY kb.MABN, bn.HOTEN
-----------------
SELECT MABS, HOTEN 
FROM BACSI
WHERE CHUYENMON = N'TAI MUI HONG'
EXCEPT 
SELECT BS.MABS, BS.HOTEN 
FROM BACSI JOIN PHUTRACH PT ON BS.MABS = PT.MABS
WHERE BATDATPHUTRACH = '2020';
--------------
SELECT bs.MABS, bs.HOTEN 
FROM BACSI bs 
JOIN PHUTRACH pt ON bs.MABS = pt.MABS
JOIN KHAMBENH kb ON pt.MAKB = kb.MAKB
JOIN BENHNHAN bn ON bn.MABN = kb.MABN
wHERE bs.CHUYENMON = M'HOI SUC CAP CUU' AND bn.HOTEN = N'NGUYEN VAN A';
GROUP BY bs.MABS, bs.HOTEN;
HAVING COUNT(DISTINCT kb.MAKB)
       =(SELECT COUNT(MAKB)
          FROM KHAMBENH kb2
          JOIN BENHNHAN bn2 ON bn2.MABN = kb2.MABN
          WHERE bn2.HOTEN = N'NGUYEN VAN A');

----------------
SELECT TOP 1 WITH TIES bs.MABS, bs.HOTEN
FROM BACSI bs 
 JOIN PHUTRACH pt ON bs.MABS = pt.MABS
 GROUP BY bs.MABS, bs.HOTEN
 ORDER BY COUNT* DESC;
 ----------------
 SELECT TENVX 
 FROM VACXIN 
 WHERE LOAIVX = N'Vector Viru' AND HQTT > 90
 ORDER BY HQTT DESC;
 ---------------
 SELECT MADH,SL 
 FROM DATHANG md JOIN VACXIN vx ON md.MAVX = vx.MAVX
 WHERE LOAIVX = N'mRNA' AND MONTH(THGIAO) = '8' AND YEAR(THGIAO) = '2021'
 ----------
 SELECT TENDP, COUNT(DOT) AS SODOTCAP 
 FROM DIAPHUONG dp JOIN PHANBO pb ON dp.MADP = pb.MADP
 WHERE MONTH(NGAYCAP) = '6' AND YEAR(NGAYCAP) = '2021'
 GROUP BY TENDP;
--------
SELECT MADP, TENDP
FROM DIAPHUONG dp 
WHERE dp.SOFO > 1000 
EXCEPT
SELECT dp.MADP, dp.TENDP
FROM DIAPHUONG dp
JOIN PHANBO pb ON dp.MADP = pb.MADP
WHERE dp.YEAR(NGAYCAP) = 2021;

-------
SELECT TOP 1 WITH TIES dp.MADP,dp.TENDP
FROM DIAPHUONG dp
JOIN PHANBO pb ON dp.MADP = pb.MADP
GROUP BY dp.MADP,dp.TENDP
ORDER BY COUNT(*) DESC;
---------- 
SELECT nv.MaNV , nv.HoTen , p.TenPhong
FROM NHANVIEN nv JOIN PHONG p ON nv.MaPhong = p.MaPhong 
WHERE p.NhiemVu = N'Nghien cuu'
ORDER BY MaNV DESC; 